### ISSUE TITLE
 error: unknown `allow` attribute: `unstable`, #[deny(unknown_lints)] on by default

### ISSUE THREAD

**Issue by emk** [reem/rust-modifier#13]
Not quite sure what's going on here—I have a bunch of other libraries with `#![allow(unstable)]`, and they seem to be working fine.

<pre>
/home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/modifier-0.0.8/src/lib.rs:3:10: 3:18 error: unknown `allow` attribute: `unstable`, #[deny(unknown_lints)] on by default
/home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/modifier-0.0.8/src/lib.rs:3 #![allow(unstable)]
                                                                                                  ^~~~~~~~
</pre>

**Comment by reem** [comment]
Fixed.
