### ISSUE TITLE
Blanket impl breaks things

### ISSUE THREAD

**Issue by Manishearth** [reem/rust-modifier#7]
https://github.com/reem/rust-modifier/blob/master/src/lib.rs#L37

I really liked the blanked impl at first, however when using it in hyper it clashes with the `set()` method of `Headers`. `set()` is a pretty common method name, perhaps we should rename it? Or remove the blanket impl and have users explicitly impl it on structs.

**Comment by reem** [comment]
The blanket impl is gone.
